export const colors = [
  ['255, 55, 55', '赤'],
  ['83, 175, 254', '青'],
  ['158, 225, 111', '緑'],
  ['255, 132, 55', 'オレンジ'],
  ['194, 153, 103', '茶'],
  ['255, 226, 114', '黄'],
  ['222, 112, 255', '紫'],
  ['56, 216, 182', 'ターコイズ'],
  ['188, 205, 221', '灰'],
  ['34, 41, 49', '黒'],
  ['255, 255, 255', '白'],
  ['255, 115, 187', 'ピンク'],
];

export const images = [
  ['https://hpgpixer.jp/image_icons/season/summer/mushitori_boy.gif', '男の子'],
  ['https://hpgpixer.jp/image_icons/season/school_ceremony/junior_school_girl.gif', '女の子'],
  ['https://hpgpixer.jp/image_icons/animals/animal_icon/dog/golden_retriever.gif', '犬'],
  ['https://hpgpixer.jp/image_icons/vehicle/train/shinkansen_n700_3an.gif', '新幹線'],
  ['https://hpgpixer.jp/image_icons/season/xmas/santa_2022_2an.gif', 'サンタ'],
  ['https://hpgpixer.jp/image_icons/animals/animal_icon/cat/cat_11.gif', '猫'],
  ['https://hpgpixer.jp/image_icons/etc/himawari.gif', 'ひまわり'],
  ['https://hpgpixer.jp/image_icons/vehicle/train/tramway.gif', '電車'],
  ['https://hpgpixer.jp/image_icons/etc/fox_mask.gif', '狐'],
  ['https://hpgpixer.jp/image_icons/space_fantasy/space_vihicle/shuttle.gif', 'シャトル'],
  ['https://hpgpixer.jp/image_icons/vehicle/vehicle_icon/tank_11.gif', '戦車'],
  ['https://hpgpixer.jp/image_icons/season/spring/sakura.gif', '桜'],
  ['https://hpgpixer.jp/image_icons/season/winter/yukidaruma_2.gif', '雪だるま'],
  ['https://hpgpixer.jp/image_icons/season/setsubun/oni_nomen_red_2.gif', '赤鬼'],
  ['https://hpgpixer.jp/image_icons/animals/animal_icon/mammal/horce_1.gif', '馬'],
  ['https://hpgpixer.jp/image_icons/space_fantasy/space_robot/robot.gif', 'ロボット'],
  ['https://hpgpixer.jp/image_icons/animals/animal_icon/animal_etc/monster.gif', '怪獣'],
  ['https://hpgpixer.jp/image_icons/space_fantasy/space_vihicle/ufo_9.gif', 'UFO'],
  ['https://hpgpixer.jp/image_icons/season/halloween/halloween_ghost_3.gif', 'おばけ'],
  ['https://hpgpixer.jp/image_icons/vehicle/vehicle_icon/yacht.gif', 'ヨット'],
];
