export const colors = [
  { value: '83, 175, 254', /*    */ label: '青' /*         */ },
  { value: '255, 226, 114', /*   */ label: '黄' /*         */ },
  { value: '255, 115, 187', /*   */ label: 'ピンク' /*     */ },
  { value: '158, 225, 111', /*   */ label: '緑' /*         */ },
  { value: '255, 132, 55', /*    */ label: 'オレンジ' /*   */ },
  { value: '255, 55, 55', /*     */ label: '赤' /*         */ },
  { value: '194, 153, 103', /*   */ label: '茶' /*         */ },
  { value: '222, 112, 255', /*   */ label: '紫' /*         */ },
  { value: '56, 216, 182', /*    */ label: 'ターコイズ' /* */ },
  { value: '188, 205, 221', /*   */ label: '灰' /*         */ },
  { value: '34, 41, 49', /*      */ label: '黒' /*         */ },
  { value: '255, 255, 255', /*   */ label: '白' /*         */ },
];
export const BASE_URL = import.meta.env.BASE_URL;
// https://hpgpixer.jp/
export const images = [
  { value: `${BASE_URL}images/mushitori_boy.gif`, /*       */ label: '男の子' /*   */ },
  { value: `${BASE_URL}images/junior_school_girl.gif`, /*  */ label: '女の子' /*   */ },
  { value: `${BASE_URL}images/golden_retriever.gif`, /*    */ label: '犬' /*       */ },
  { value: `${BASE_URL}images/halloween_ghost_3.gif`, /*   */ label: 'おばけ' /*   */ },
  { value: `${BASE_URL}images/santa_2022_2an.gif`, /*      */ label: 'サンタ' /*   */ },
  { value: `${BASE_URL}images/cat_11.gif`, /*              */ label: '猫' /*       */ },
  { value: `${BASE_URL}images/himawari.gif`, /*            */ label: 'ひまわり' /* */ },
  { value: `${BASE_URL}images/tramway.gif`, /*             */ label: '電車' /*     */ },
  { value: `${BASE_URL}images/fox_mask.gif`, /*            */ label: '狐' /*       */ },
  { value: `${BASE_URL}images/shuttle.gif`, /*             */ label: 'シャトル' /* */ },
  { value: `${BASE_URL}images/tank_11.gif`, /*             */ label: '戦車' /*     */ },
  { value: `${BASE_URL}images/sakura.gif`, /*              */ label: '桜' /*       */ },
  { value: `${BASE_URL}images/yukidaruma_2.gif`, /*        */ label: '雪だるま' /* */ },
  { value: `${BASE_URL}images/oni_nomen_red_2.gif`, /*     */ label: '赤鬼' /*     */ },
  { value: `${BASE_URL}images/horce_1.gif`, /*             */ label: '馬' /*       */ },
  { value: `${BASE_URL}images/robot.gif`, /*               */ label: 'ロボット' /* */ },
  { value: `${BASE_URL}images/monster.gif`, /*             */ label: '怪獣' /*     */ },
  { value: `${BASE_URL}images/ufo_9.gif`, /*               */ label: 'UFO' /*      */ },
  { value: `${BASE_URL}images/shinkansen_n700_3an.gif`, /* */ label: '新幹線' /*   */ },
  { value: `${BASE_URL}images/yacht.gif`, /*               */ label: 'ヨット' /*   */ },
];

export const housings = [
  `${BASE_URL}images/housing_01.gif`,
  `${BASE_URL}images/housing_02.gif`,
  `${BASE_URL}images/housing_03.gif`,
  `${BASE_URL}images/housing_04.gif`,
  `${BASE_URL}images/housing_05.gif`,
  `${BASE_URL}images/housing_06.gif`,
  `${BASE_URL}images/housing_07.gif`,
  `${BASE_URL}images/housing_08.gif`,
  `${BASE_URL}images/housing_09.gif`,
  `${BASE_URL}images/housing_10.gif`,
  `${BASE_URL}images/housing_11.gif`,
];
