/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InputCommafyNumber: typeof import('./component/InputCommafyNumber.vue')['default']
    MyDropdown: typeof import('./component/MyDropdown.vue')['default']
    OnClickOutside: typeof import('@vueuse/components')['OnClickOutside']
    Roulette: typeof import('./component/Roulette.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
